// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdslprshnafmhsqimuqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkc2xwcnNobmFmbWhzcWltdXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzY3MzMsImV4cCI6MjA2MDY1MjczM30.PwWs5nulUdqWn9LgRksodDT3i5n8ZBCy12kXME2UuxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);